### ISSUE TITLE
Error in Android + Termux due to missing /tmp/ directory

### ISSUE THREAD

**Issue by Bugzey** [Bugzey/speak-to-file#3]
**Describe the bug**
Producing audio files in Android under Termux causes an error due to a nonexistent /tmp/ directory.

**To Reproduce**
1. Install the program using Python and Pip in an Android Termux terminal
2. Pass any text to the program
3. Receive an error

**Expected behavior**
Audio is produced correctly.

**Screenshots**

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi A1
- OS: Android 9
- Environment: Termux

**Additional context**

```{python}
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/speak_to_file/__main__.py", line 2, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/speak_to_file/speak_to_file.py", line 341, in main
    execute_read_convert(out_dir, out_file, text, title, text_file, reader_command, converter_command, overwrite, reader_args, converter_args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/speak_to_file/speak_to_file.py", line 236, in execute_read_convert
    with open(text_file, 'w+') as file_object:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/logo'
```

**Comment by Bugzey** [comment]
Consider using the built-in `tempfile` library:

https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
